version: "3"

services:
  creditapplicationsystem:
    container_name: "creditapplicationsystem"
    build: .
    environment:
      - spring.datasource.url=jdbc:mysql://creditSystemDb:3306/creditSystem?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.cache.type=redis
      - spring.redis.host=redisCache
      - spring.redis.port=6379
    ports:
      - "8080:8080"
    depends_on:
     - creditSystemDb
     - rabbitmq
     - redisCache
    networks:
      - host

  creditSystemDb:
    container_name: "creditSystemDb"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: creditSystem
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD : root
    networks:
      - host
    volumes:
      - dbdata:/var/lib/mysql

  redisCache:
    container_name: "redisCache"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - host

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  dbdata: